modLoader = "javafml" #mandatory
loaderVersion = "${loader_version_range}" #mandatory
license = "${mod_license}"

[[mods]] #mandatory
modId = "${mod_id}" #mandatory
version = "${mod_version}" #mandatory
displayName = "${mod_name}" #mandatory
authors = "${mod_authors}" #optional
description = '''${mod_description}'''

# --- Dependencies ---

# Forge
[[dependencies."${mod_id}"]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

# Minecraft
[[dependencies."${mod_id}"]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

# Curios API (変数は使わず直接指定してエラーを回避)
[[dependencies."${mod_id}"]]
modId = "curios"
mandatory = true
versionRange = "[5.0.0,)"
ordering = "NONE"
side = "BOTH"

# FDLib (変数は使わず直接指定してエラーを回避)
[[dependencies."${mod_id}"]]
modId = "fdlib"
mandatory = true
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"